server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # try_files necesario para que react-router-dom maneje rutas como /admin
    # sin que Nginx devuelva 404 al no encontrar el fichero físicamente.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
